Homework 4
Grundelb/grigorii-shakhin-test-automation pull request #4
Opened 2022-12-19 20:35 UTC by Grundelb

2022-12-21 20:21 UTC, account0809 requested changes

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/WebDriverSetup.java
> +        new WebDriverWait(driver, 10, 1000);
It's better to add some condition to wait

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/WebDriverSetup.java
> +        //Close Browser
Please, do not use one row comments, code must be written the way it is easy to follow by method/class/variable names

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExercise1.java
> +        softly.assertThat(driver.getTitle()).contains("Home Page");
Please, move all strings to class constants

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExercise1.java
> +        softly.assertThat(driver.findElement(By.id("user-name")).getText())
It's better to receive actual text first and then use it in the assertion

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExercise1.java
> +                        + "/parent::div/following-sibling::span[@class = 'benefit-txt']"))
It's better to keep xpath as short as possible, without a multiple folding, in order not to make tests unstable in future

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExercise1.java
> +                        + "[@class='icons-benefit icon-practise']"
All locators must be out of test, for now, at least in class constants

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExercise1.java
> +        jse.executeScript("window.scrollBy(0,-500)");
Please, keep magic numbers out of tests, only 0 and 1 are allowed

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExercise1.java
> +public class TestExercise1 extends WebDriverSetup {
Please, do not use numbers in classes name

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex2/TestExercise2.java
> +    public void checkExercice2() {
please, use description parameter of annotation to define what exercise the task is devoted to

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex2/TestExercise2.java
> +        softly.assertThat(driver.getTitle()).contains("Home Page");
It's better to separate complicated tests with different types of verification steps to separate tests

2022-12-21 20:21 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex2/TestExercise2.java
> +    }
assertAll

2022-12-28 19:09 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExerciseCheckMainPage.java
> +        softly.assertThat(actualUserName).isEqualTo("ROMAN IOVLEV");
It's better to perform assertAll() in every test, not to leave at to the latest tests in a scope

2022-12-28 19:09 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/WebDriverSetup.java
> +        softly.assertAll();
It's better to cause assertAll() in every test at the end

2022-12-28 19:09 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/WebDriverSetup.java
> +    protected final int timeOutWaits = 10;
If a variable is not in use in child classes and there is no need to share it, it would be good to make it private

2023-01-10 23:41 UTC, account0809 requested changes

2023-01-10 23:41 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/WebDriverSetup.java
> +        softly.assertAll();
not resolved

2023-01-10 23:41 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExerciseCheckMainPage.java
> +        softly.assertThat(actualUserName).isEqualTo("ROMAN IOVLEV");
not resolved

2023-01-10 23:41 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExerciseCheckMainPage.java
> +    }
please, keep constants as class variables

2023-01-11 09:05 UTC, Grundelb commented on src/test/java/com/epam/tc/hw2/WebDriverSetup.java
> +        softly.assertAll();
@account0809 Could you please specify why this point is not resolved? I put asset all function in method and used @AfterMethod annotation to apply for all tests.
`@AfterMethod
    protected void completeSoftAssert() {
        softly.assertAll();`

2023-01-11 11:31 UTC, Grundelb commented on src/test/java/com/epam/tc/hw2/ex1/TestExerciseCheckMainPage.java
> +        softly.assertThat(actualUserName).isEqualTo("ROMAN IOVLEV");
@account0809 Could you please specify why this point is not resolved? I put asset all function in method and used @AfterMethod annotation to apply for all tests.

2023-01-12 02:32 UTC, account0809 commented on src/test/java/com/epam/tc/hw2/ex1/TestExerciseCheckMainPage.java
> +        softly.assertThat(actualUserName).isEqualTo("ROMAN IOVLEV");
It's better to use softAssert only where it is required (several verifications in one test method), in other cases where only one assert is required it's worth using one common assert (from jUnit, testNg, assertJ and so on). So there is no reason to put assertAll in afterMethod, because it is not required everywhere.

2023-01-12 02:35 UTC, account0809 approved these changes
Please, use soft/hard assertion according to a need in the next PRs

2023-01-12 11:09 UTC, merged